apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ .Values.gatewayClass.name }}
  labels:
    {{- include "eks-gateway-proxy.labels" . | nindent 4 }}
spec:
  controllerName: {{ .Values.gatewayClass.controllerName | quote }}
