apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "eks-gateway-proxy.labels" . | nindent 4 }}
spec:
  gatewayClassName: {{ .Values.gatewayClass.name }}
  listeners:
    - name: http
      protocol: {{ .Values.gateway.listener.protocol }}
      port: {{ .Values.gateway.listener.port }}
      allowedRoutes:
        namespaces:
          from: All
