apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.httpRoute.name }}
  namespace: {{ .Values.httpRoute.backend.service.namespace }}
  labels:
    {{- include "eks-gateway-proxy.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      namespace: {{ .Release.Namespace }}
  hostnames:
    - {{ .Values.httpRoute.hostname | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: "/"
      backendRefs:
        - name: {{ .Values.httpRoute.backend.service.name }}
          port: {{ .Values.httpRoute.backend.service.port }}
          kind: Service
          namespace: {{ .Values.httpRoute.backend.service.namespace }}
